# Generated by Django 5.0.1 on 2024-01-17 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='designation',
            field=models.CharField(choices=[('mgr', 'Manager'), ('sd', 'Software developer'), ('pl', 'Project leader')], max_length=50),
        ),
    ]
